version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: srv
    container_name: srv_container
    restart: always
    environment:
      NUM_WORKERS: 2
    ports:
      - "8001:8001"
    env_file:
      - .env

