# Generated by Django 2.1.3 on 2018-12-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=20, unique=True, verbose_name="Производитель"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("patronymic_name", models.CharField(max_length=30, verbose_name="Отчество")),
                ("tell", models.CharField(max_length=13, unique=True, verbose_name="Телефонный номер")),
                ("addres", models.CharField(blank=True, max_length=200, verbose_name="Адресс")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Почта")),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SparPart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="Наименование")),
                ("part_num", models.CharField(blank=True, max_length=30, unique=True, verbose_name="Парт номер")),
                ("specification", models.TextField(max_length=2000, verbose_name="Описание")),
            ],
        ),
        migrations.CreateModel(
            name="TypeAppliances",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type_appliances",
                    models.CharField(blank=True, max_length=50, unique=True, verbose_name="Вид техники"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeSparPart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type_spar_part",
                    models.CharField(blank=True, max_length=50, unique=True, verbose_name="Тип запчасти"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sparpart",
            name="attachment_appliances",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_for_appliances",
                to="srvbd.TypeAppliances",
            ),
        ),
        migrations.AddField(
            model_name="sparpart",
            name="attachment_manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment_for_manufacturer",
                to="srvbd.Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="sparpart",
            name="attachment_part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachment_for_part", to="srvbd.TypeSparPart"
            ),
        ),
    ]
