# Generated by Django 2.1.3 on 2019-01-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('out_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('detail_name', models.ForeignKey(on_delete=None, related_name='detail_spar_part', to='srvbd.SparPart')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_date', models.DateField(auto_now_add=True)),
                ('exchange_rates', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('specification', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer',
            field=models.CharField(max_length=20, unique=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='typeappliances',
            name='type_appliances',
            field=models.CharField(max_length=50, unique=True, verbose_name='Вид техники'),
        ),
        migrations.AlterField(
            model_name='typesparpart',
            name='type_spar_part',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип запчасти'),
        ),
        migrations.AddField(
            model_name='incominglist',
            name='Ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attash_incoming_list', to='srvbd.Shipper'),
        ),
        migrations.AddField(
            model_name='incominglist',
            name='detail_incoming',
            field=models.ForeignKey(on_delete=None, related_name='incom_detail', to='srvbd.Detail'),
        ),
    ]
