# Generated by Django 2.1.3 on 2019-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0010_detail_detailinlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='statys',
            field=models.BooleanField(default=False),
        ),
    ]
