# Generated by Django 2.1.3 on 2019-01-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0013_auto_20190124_1910"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailinlist",
            old_name="detail_name",
            new_name="spar_part",
        ),
    ]
