# Generated by Django 2.1.3 on 2019-01-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0014_auto_20190124_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='detail_incoming',
        ),
    ]
