# Generated by Django 2.1.3 on 2019-02-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0017_auto_20190221_2320"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetailInList",
            new_name="DetailInIncomList",
        ),
    ]
