# Generated by Django 2.1.3 on 2019-03-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0020_auto_20190306_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespersoninvoice',
            name='invoice_sum',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
