# Generated by Django 2.1.3 on 2019-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0024_auto_20190317_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsaleobject',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='materialsaleobject',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
