# Generated by Django 2.1.3 on 2019-03-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0027_auto_20190323_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='exchange_ratest',
            new_name='exchange_rates',
        ),
    ]
