# Generated by Django 2.1.3 on 2019-03-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0028_auto_20190324_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinincomlist',
            name='selector_incom',
        ),
    ]
