# Generated by Django 2.1.3 on 2019-03-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0030_detailinincomlist_selector_incom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incoming",
            old_name="exchange_rates",
            new_name="exchange_ratest",
        ),
    ]
