# Generated by Django 2.1.3 on 2019-03-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0033_auto_20190325_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='exchange_rates',
        ),
    ]
