# Generated by Django 2.1.3 on 2019-03-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0036_auto_20190326_2029"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incoming",
            old_name="exchange_ratest",
            new_name="exchange_rates",
        ),
    ]
