# Generated by Django 2.1.3 on 2019-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0037_auto_20190326_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
    ]
