# Generated by Django 2.1.3 on 2019-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0038_detail_status_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespersoninvoice',
            name='payment_state',
            field=models.BooleanField(default=False),
        ),
    ]
