# Generated by Django 2.1.3 on 2020-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0045_shipper_store_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.FloatField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
