# Generated by Django 2.1.3 on 2020-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0046_auto_20200527_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_role',
            field=models.CharField(choices=[('MA', 'Мастер'), ('CL', 'Клиент')], default='CL', max_length=2),
        ),
    ]
