# Generated by Django 2.1.3 on 2020-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0048_auto_20200527_2311"),
    ]

    operations = [
        migrations.AddField(
            model_name="incoming",
            name="currency",
            field=models.CharField(choices=[("UAN", "UAN"), ("EUR", "EUR")], default="UAN", max_length=3),
        ),
    ]
