# Generated by Django 2.1.3 on 2020-07-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0049_incoming_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('EUR', 'EUR')], default='UAH  ', max_length=3),
        ),
    ]
