# Generated by Django 2.1.3 on 2020-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0051_auto_20200806_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialsaleobject",
            name="own_margin",
            field=models.FloatField(default=1),
        ),
    ]
