# Generated by Django 2.1.3 on 2020-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0052_materialsaleobject_own_margin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialsaleobject",
            name="own_margin",
        ),
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(choices=[("MA", "Мастер"), ("CL", "Клиент")], default="CL", max_length=2),
        ),
    ]
