# Generated by Django 2.2.28 on 2022-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srvbd", "0054_auto_20200904_2259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incoming",
            name="currency",
            field=models.CharField(choices=[("UAH", "UAH"), ("EUR", "EUR")], default="UAH", max_length=3),
        ),
    ]
