# Generated by Django 2.2.28 on 2023-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvbd', '0057_auto_20230517_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparpart',
            name='part_num',
            field=models.TextField(null=True),
        ),
    ]
